version: '3.9'

networks:
  TaskManager.Network:
    name: TaskManager.Network

services:
  taskmanager.postgres:
    image: postgres:latest
    container_name: TaskManager.Postgres
    hostname: TaskManager.Postgres
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - ./.container/postgres:/var/lib/postgresql
      - ./.container/postgres:/var/log/postgresql
    command: -p 5432
    networks:
      - TaskManager.Network

volumes:
    postgres:
      driver: local