// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskManager.Modules.Management.Infrastructure.Database;

#nullable disable

namespace TaskManager.Modules.Management.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ManagementsDbContext))]
    [Migration("20240722152714_FixedTeamUser")]
    partial class FixedTeamUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("management")
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskManager.Modules.Management.Domain.Groups.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Teams", "management");
                });

            modelBuilder.Entity("TaskManager.Modules.Management.Domain.Groups.Entities.TeamTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Priority")
                        .HasColumnType("boolean");

                    b.Property<int>("Progress")
                        .HasColumnType("integer");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamTasks", "management");
                });

            modelBuilder.Entity("TaskManager.Modules.Management.Domain.Groups.Entities.TeamUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("TeamUsers", "management");
                });

            modelBuilder.Entity("TaskManager.Modules.Management.Domain.Groups.Entities.Team", b =>
                {
                    b.OwnsMany("TaskManager.Abstractions.Kernel.ValueObjects.User.UserId", "UserIds", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("UserIds")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("UserIds");

                            b1.HasKey("Id");

                            b1.HasIndex("UserIds");

                            b1.ToTable("TeamUserIds", "management", t =>
                                {
                                    t.Property("UserIds")
                                        .HasColumnName("UserIds1");
                                });

                            b1.WithOwner()
                                .HasForeignKey("UserIds");
                        });

                    b.Navigation("UserIds");
                });

            modelBuilder.Entity("TaskManager.Modules.Management.Domain.Groups.Entities.TeamTask", b =>
                {
                    b.HasOne("TaskManager.Modules.Management.Domain.Groups.Entities.Team", null)
                        .WithMany("TeamTasks")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TaskManager.Modules.Management.Domain.Groups.Entities.Team", b =>
                {
                    b.Navigation("TeamTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
